- name: apt | Update all packages to their latest version
  become: yes
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: apt | install necessary ubuntu packages
  become: yes
  apt:
    pkg:
      - curl
      - vim
      - git
      - gh
      - python3
      - bpython
      - fonts-firacode
      - screen
      - fzf
      - ripgrep
      - mariadb-server
      - byobu 
      - gnome-tweaks

- name: systemd_service | enable mariadb.service
  systemd:
    name: mariadb.service
    state: started
    daemon_reload: true
    enabled: true
    
